name: Build and Deploy

on:
  push:
    paths:
      - 'app/run.py'
    branches:
      - main

env:
  IMAGE_NAME: yyyeunn/qwen3

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get short commit SHA
        id: commit
        run: echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build and Push Docker Image
        run: |
          docker build -t $IMAGE_NAME:${{ steps.commit.outputs.sha }} ./app
          docker push $IMAGE_NAME:${{ steps.commit.outputs.sha }}

      - name: Update values.yaml image.tag
        run: |
          sed -i "s/^  tag: .*$/  tag: ${{ steps.commit.outputs.sha }}/" qwen3/values.yaml

      - name: Package Helm Chart
        run: |
          helm package qwen3
          mkdir -p chart-out
          mv qwen3-*.tgz chart-out/

      - name: Create or Update index.yaml
        run: |
          helm repo index chart-out --url https://yyyeun.github.io/Qwen3-helm

      - name: Push to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: chart-out
